### ISSUE TITLE
Any way to add vips with the bot?

### ISSUE THREAD

**Issue by LyykaPaws** [ilias-sp/Twitch-Chat-Bot-PHP#5] opened 2018-12-25 23:48 UTC
Hi there! I was wondering if there was any way to add VIPs with this bot?

**Comment by ilias-sp** [comment] 2018-12-26 01:04
hi! its not supported as of now. If you dont mind explaining how it should work, i could take a look on implementing it. my questions are (took a fast look at documentation):

- who should be able to use the /vip and /unvip commands? all bot admins or just the channel owner?
- why would the owner require to do these /vip /unvip commands via the bot and not directly? am i missing something?

thx

**Comment by LyykaPaws** [comment] 2018-12-27 23:27
It would probably be best for all bot admins, or channel moderators. And to give an example, I have moderators I trust to give VIP badges, and this would help out tremendously, so that they can give it out instead of forcing me out of game to do it, y'know?

**Comment by ilias-sp** [comment] 2018-12-28 01:04
ok, adding the capability. But one remark: 

When i am trying the /vip /unvip command, i get this response:

`Unable to add VIP. Visit the Achievements page on your dashboard to learn how to unlock this feature.`

This implies that if you are running the bot under a dedicated user, that user has to have earned the privilege to use the /vip /unvip commands - not familiar how that can be achieved.

anyway, i will enhance the code - as its a straight forward implementation - plz check back tomorrow and it will be there!

**Comment by LyykaPaws** [comment] 2018-12-29 03:47
Awesome! Thanks! To my understanding, the bot would have to run the VIP Command through the streamers account, instead of on the bot account, though, which is the only thing I'm worried about.

**Comment by ilias-sp** [comment] 2018-12-29 11:40
`the bot would have to run the VIP Command through the streamers account, instead of on the bot account`

That would be great but thats not how Twitch chat works :( You could run the bot using your own (the Streamer) account, but i agree it is ugly. You could read about VIPs feature and see if you can circumvent the issue somehow (like if Streamer can whitelist which users can manage the VIPs list), with a fast look i didn't see something.

anyhow, good luck!

**Comment by ilias-sp** [comment] 2018-12-29 11:41
i guess we can close the issue

**Closed as completed by ilias-sp** 2018-12-29 11:41 UTC

**Comment by donavynelliott** [comment] 2019-02-17 02:02
>             if (isset($json_response['chatters']['vips']))
            {
                $viewers_in_json = array_merge($viewers_in_json, $json_response['chatters']['vips']);
            }

**Comment by darkwolfie37** [comment] 2022-03-05 11:45
> ok, adding the capability. But one remark:
> 
> When i am trying the /vip /unvip command, i get this response:
> 
> `Unable to add VIP. Visit the Achievements page on your dashboard to learn how to unlock this feature.`
> 
> This implies that if you are running the bot under a dedicated user, that user has to have earned the privilege to use the /vip /unvip commands - not familiar how that can be achieved.
> 
> anyway, i will enhance the code - as its a straight forward implementation - plz check back tomorrow and it will be there!

Did you try this feature on the bots own twitch chat, if so thats why you ran into this error.

mods that dont have vip added yet on their channels are allowed to give vip to someone else if a they are a mod on a nother persons stream. Thanks

**Comment by ilias-sp** [comment] 2022-03-05 16:52
hi @darkwolfie37 ,

> Did you try this feature on the bots own twitch chat, if so thats why you ran into this error.

indeed, i had been testing the bot running as my personal account, and on my channel, tried again just now, i still get the same message, thanks for clarifying that this is by design behavior.

**Comment by darkwolfie37** [comment] 2022-03-05 18:43
your welcome

I also am going to edit some of the code to update things. after you removed the twitch api from the project the loyatly points system doesnt work so I am going to look into how the chatters are sent in since its throws errors to my php. Also a I Will be making a official tutorial video for this project. Hope to see you here again soon! -DarkWolfie

**Comment by ilias-sp** [comment] 2022-03-05 19:03
hello, 

glad you are using the bot :)

I just tried the loyalty points, it seems to work for me. Just to remind that to enable the feature, you need to set the `loyalty_points_per_interval` to a non-zero value:

```
// how many points a viewers is awarded per check interval. if you set it to 0, feature is disabled:
$config['loyalty_points_per_interval'] = 0;
$config['loyalty_currency'] = 'IzyEuro';
$config['loyalty_check_interval'] = 30; // in seconds
$config['loyalty_points_welcome_award'] = 1000; // amount of LP awarded to new viewers
$config['loyaltypoints_keyword'] = '!izyeuros';
```
